Repository abhaygupta12/HackTobetter_Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#10 added BFS Traversal code in cpp
  BFS_Traversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#11 Added code for break-a-palindrome (LeetCode) CPP
  break-a-palindrome
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#14 Create insertionsort.cpp
  insertionsort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#15 binary-tree-inorder-traversal
  binary-tree-inorder-traversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#18 Created AddTwoNumbersAsLinkedList.cpp
  AddTwoNumbersAsLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#21 Added AtCoder Dp Solutions
  AtCoder Dp Contest Solution/A.cpp
  AtCoder Dp Contest Solution/B.cpp
  AtCoder Dp Contest Solution/C.cpp
  AtCoder Dp Contest Solution/D.cpp
  AtCoder Dp Contest Solution/E.cpp
  AtCoder Dp Contest Solution/F.cpp
  AtCoder Dp Contest Solution/G.cpp
  AtCoder Dp Contest Solution/H.cpp
  AtCoder Dp Contest Solution/I.cpp
  AtCoder Dp Contest Solution/J.cpp
  AtCoder Dp Contest Solution/K.cpp
  AtCoder Dp Contest Solution/L.cpp
  AtCoder Dp Contest Solution/M.cpp
  AtCoder Dp Contest Solution/N.cpp
  AtCoder Dp Contest Solution/O.cpp
  AtCoder Dp Contest Solution/P.cpp
  AtCoder Dp Contest Solution/Q.cpp
  AtCoder Dp Contest Solution/R.cpp
  AtCoder Dp Contest Solution/S.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#22 create Check_anagarams
  Check_anagarams.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#23 Adding Trie
  Trie.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#24 Add files via upload
  1071. Greatest Common Divisor of Strings.cpp
  263. Ugly Number.cpp
  264. Ugly Number II.cpp
  836. Rectangle Overlap.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#25 Sorting Algorithms Added
  Insertion Sort.cpp
  Swap Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#26 Linear search in all languages
  Linear Search/linear_search.cpp
  Linear Search/linear_search.java
  Linear Search/linear_search.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#27 Create Lowest Common Ancestor of a Binary Tree
  Lowest Common Ancestor of a Binary Tree
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#31 RECB community
  TwoOddOccuring.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#34 Add files via upload
  DAA Merge sort.cpp
  circular linked list.cpp
  doubly linked list.cpp
Labels: help wanted, hacktoberfest-accepted, hacktoberfest

#33 Added Dijkstra’s Shortest Path Algorithm
  Dijkstra’s Shortest Path Algorithm/Dijkstra.c
  Dijkstra’s Shortest Path Algorithm/Dijkstra.cpp
  Dijkstra’s Shortest Path Algorithm/Dijkstra.cs
  Dijkstra’s Shortest Path Algorithm/Dijkstra.java
  Dijkstra’s Shortest Path Algorithm/Dijkstra.js
  Dijkstra’s Shortest Path Algorithm/Dijkstra.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#32 Create Valid Parenthesis
  Valid Parenthesis
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#30 Create QuickSort.cpp
  QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#29 Create Invisible_Cloak.py
  Invisible_Cloak.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#35 Create Dijkstra_shortest_path.cpp
  Dijkstra_shortest_path.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#36 Added an example code to use comparable interface in Java
  Java_Comparable_Interface_use_case/sort_cities_by_population.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#37 Create merge_sort.java
  merge_sort.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022

#38 Create 1578- Minimum-Time to-Make-Rope-Colorful.cpp
  1578- Minimum-Time to-Make-Rope-Colorful.cpp
Labels: good first issue, hacktoberfest, hacktoberfast2022

#40 Added Several Problem Solving Questions done in C++
  125-valid-palindrome/125-valid-palindrome.cpp
  125-valid-palindrome/README.md
  167-two-sum-ii-input-array-is-sorted/167-two-sum-ii-input-array-is-sorted.cpp
  167-two-sum-ii-input-array-is-sorted/NOTES.md
  167-two-sum-ii-input-array-is-sorted/README.md
  189-rotate-array/189-rotate-array.cpp
  189-rotate-array/NOTES.md
  189-rotate-array/README.md
  191-number-of-1-bits/191-number-of-1-bits.cpp
  191-number-of-1-bits/NOTES.md
  191-number-of-1-bits/README.md
  35-search-insert-position/35-search-insert-position.cpp
  35-search-insert-position/NOTES.md
  35-search-insert-position/README.md
  53-maximum-subarray/53-maximum-subarray.cpp
  53-maximum-subarray/NOTES.md
  53-maximum-subarray/README.md
  69-sqrtx/69-sqrtx.cpp
  69-sqrtx/NOTES.md
  69-sqrtx/README.md
  7-reverse-integer/7-reverse-integer.cpp
  7-reverse-integer/NOTES.md
  7-reverse-integer/README.md
  88-merge-sorted-array/88-merge-sorted-array.cpp
  88-merge-sorted-array/NOTES.md
  88-merge-sorted-array/README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfast2022
